# Generated by Django 4.2.5 on 2023-09-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='score',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='participant',
            name='negative_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date',
            field=models.DateField(),
        ),
    ]
