# Generated by Django 4.2.5 on 2023-09-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_score_participant_negative_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='challenge',
        ),
        migrations.AddField(
            model_name='challenge',
            name='sample',
            field=models.ManyToManyField(related_name='challenge', to='challenges.sample'),
        ),
    ]
